version: "3"
services:
  postgresql:
    image: postgres:12
    container_name: postgresql_yay
    ports:
      - 54320:5432
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
